import javax.swing.JOptionPane;
import java.io.File;
import java.io.FileReader;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Administrator
 */
public class login extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public login() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField2 = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPasswordField1 = new javax.swing.JPasswordField();

        jTextField2.setText("jTextField2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Personal activity management");

        jButton1.setText("Login");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Tên Đăng Nhập");

        jLabel2.setText("Mật Khẩu");
        jLabel2.setPreferredSize(new java.awt.Dimension(83, 16));

        jButton2.setText("Đăng Nhập");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Tạo Tài Khoản");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jPasswordField1))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton3)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(jPasswordField1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(101, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    String user = jTextField1.getText().trim();
    String pass = new String(jPasswordField1.getPassword()).trim();

    
    if (user.length() < 5 || user.length() > 10) {
        JOptionPane.showMessageDialog(this, "Tên đăng nhập phải từ 5 đến 10 ký tự");
        return;
    }
    if (pass.length() < 5 || pass.length() > 10) {
        JOptionPane.showMessageDialog(this, "Mật khẩu phải từ 5 đến 10 ký tự");
        return;
    }

    boolean found = false;

    try {
        File file = new File("ThongTin.txt");
        if (!file.exists()) {
            JOptionPane.showMessageDialog(this, "Chưa có dữ liệu tài khoản!");
            return;
        }

        BufferedReader br = new BufferedReader(new FileReader(file));
        String line;

        String tk = "";
        String mk = "";
        boolean readingAccount = false;

        while ((line = br.readLine()) != null) {

            
            if (line.equals("#ACCOUNT")) {
                readingAccount = true;
                tk = "";
                mk = "";
                continue;
            }

            if (readingAccount) {

                if (line.startsWith("TK=")) {
                    tk = line.substring(3).trim();
                    continue;
                }

                if (line.startsWith("MK=")) {
                    mk = line.substring(3).trim();
                    continue;
                }

                
                if (line.startsWith("#DAY")) {
                    // Kiểm tra tài khoản đã đọc
                    if (user.equals(tk) && pass.equals(mk)) {
                        found = true;
                        break;
                    }
                    readingAccount = false;
                }
            }
        }

        
        if (!found && readingAccount) {
            if (user.equals(tk) && pass.equals(mk)) {
                found = true;
            }
        }

        br.close();

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Lỗi đọc file!");
        return;
    }

    if (found) {
        JOptionPane.showMessageDialog(this, "Đăng nhập thành công!");

        
        Ud home = new Ud(user, pass);
        home.setVisible(true);
        this.dispose();

    } else {
        JOptionPane.showMessageDialog(this, "Sai TK/MK hoặc chưa tạo tài khoản!");
    }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
    String user = jTextField1.getText().trim();
    String pass = new String(jPasswordField1.getPassword()).trim();

    // KIỂM TRA ĐỘ DÀI
    if (user.length() < 5) {
        JOptionPane.showMessageDialog(this, "Tên tài khoản phải trên 5 ký tự!");
        return;
    }
    if (pass.length() < 5) {
        JOptionPane.showMessageDialog(this, "Mật khẩu phải trên 5 ký tự!");
        return;
    }

    // KIỂM TRA TK ĐÃ TỒN TẠI
    try {
        File file = new File("ThongTin.txt");
        if (!file.exists()) {
            file.createNewFile();
        }

        BufferedReader br = new BufferedReader(new FileReader(file));
        String line, tk = "";
        boolean readingAccount = false;

        while ((line = br.readLine()) != null) {

            if (line.equals("#ACCOUNT")) {
                readingAccount = true;
                tk = "";
                continue;
            }

            if (readingAccount) {
                if (line.startsWith("TK=")) {
                    tk = line.substring(3).trim();
                }

                if (line.startsWith("#DAY")) {
                    if (user.equals(tk)) {
                        JOptionPane.showMessageDialog(this, "Tài khoản đã tồn tại!");
                        br.close();
                        return;
                    }
                    readingAccount = false;
                }
            }
        }
        br.close();

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Lỗi kiểm tra tài khoản!");
        return;
    }

    // GHI TÀI KHOẢN MỚI — THEO ĐÚNG FORM BẠN MẪU
    try {
        BufferedWriter bw = new BufferedWriter(new FileWriter("ThongTin.txt", true));

        bw.write("#ACCOUNT\n");
        bw.write("TK=" + user + "\n");
        bw.write("MK=" + pass + "\n");

        // 3 ngày mặc định rỗng
        for (int i = 1; i <= 3; i++) {
            bw.write("#DAY:-" + i + "\n");
            bw.write("Hoạt động 1: \n");
            bw.write("Hoạt động 2: \n");
            bw.write("Hoạt động 3: \n");
            bw.write("Hoạt động 4: \n");
            bw.write("Hoạt động 5: \n");
            bw.write("TICK: \n");
            bw.write("NOTE: \n");
        }

        bw.write("\n"); // dòng trống tách tài khoản

        bw.close();

        JOptionPane.showMessageDialog(this, "Tạo tài khoản thành công!");

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Lỗi lưu tài khoản!");
        e.printStackTrace();
    }
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
